# 返回最小元素的栈
cc_test(
  name = "stack_get_min",
  srcs = ["stack_get_min.cc"],
  deps = [
    "@com_google_googletest//:gtest_main"
  ]
)

# 判断一个数是不是回文数
cc_test(
  name = "palindrome_number",
  srcs = ["palindrome_number.cc"],
  deps = [
    "@com_google_googletest//:gtest_main"
  ]
)

