# Leetcode 通用树结点
cc_library(
  name = "leetcode_tree_node",
  hdrs = ["treenode.hpp"],
)

cc_test(
  name = "treenode_test",
  srcs = ["treenode_test.cc"],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 100: Same Tree
cc_test(
  name = "leetcode100",
  srcs = [
    "leetcode100_same_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 104: Maximum Depth of Binary Tree
cc_test(
  name = "leetcode104",
  srcs = [
    "leetcode104_maximum_depth_of_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 111: Minimum Depth of Binary Tree
cc_test(
  name = "leetcode111",
  srcs = [
    "leetcode111_minimum_depth_of_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 226: Invert Binary Tree
cc_test(
  name = "leetcode226",
  srcs = [
    "leetcode226_invert_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 292: Nim Game
cc_test(
  name = "leetcode292",
  srcs = [
    "leetcode292_nim_game.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)