# Leetcode 通用树结点
cc_library(
  name = "leetcode_tree_node",
  hdrs = ["treenode.hpp"],
)

cc_test(
  name = "treenode_test",
  srcs = ["treenode_test.cc"],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 通用链表结点
cc_library(
  name = "leetcode_link_list_node",
  hdrs = ["linklist.hpp"],
)

cc_test(
  name = "linklist_test",
  srcs = ["linklist_test.cc"],
  deps = [
    ":leetcode_link_list_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 27: Remove Element
cc_test(
  name = "leetcode27",
  srcs = [
    "leetcode27_remove_element.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)


# Leetcode 83: Remove Duplicates From Sorted List
cc_test(
  name = "leetcode83",
  srcs = [
    "leetcode83_remove_duplicates_from_sorted_list.cc"
  ],
  deps = [
    ":leetcode_link_list_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 100: Same Tree
cc_test(
  name = "leetcode100",
  srcs = [
    "leetcode100_same_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 104: Maximum Depth of Binary Tree
cc_test(
  name = "leetcode104",
  srcs = [
    "leetcode104_maximum_depth_of_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 111: Minimum Depth of Binary Tree
cc_test(
  name = "leetcode111",
  srcs = [
    "leetcode111_minimum_depth_of_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 169: Majority Element
cc_test(
  name = "leetcode169",
  srcs = [
    "leetcode169_majority_element.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 171: Excel Sheet Column Number
cc_test(
  name = "leetcode171",
  srcs = [
    "leetcode171_excel_sheet_column_number.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 191: Number of 1 Bits
cc_test(
  name = "leetcode191",
  srcs = [
    "leetcode191_numbers_of_1_bits.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 206: Reverse Linked List
cc_test(
  name = "leetcode206",
  srcs = [
    "leetcode206_reverse_linked_list.cc"
  ],
  deps = [
    ":leetcode_link_list_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 217: Contains Duplicate
cc_test(
  name = "leetcode217",
  srcs = [
    "leetcode217_contains_duplicate.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 226: Invert Binary Tree
cc_test(
  name = "leetcode226",
  srcs = [
    "leetcode226_invert_binary_tree.cc"
  ],
  deps = [
    ":leetcode_tree_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 237: Delete Node in a Linked List
cc_test(
  name = "leetcode237",
  srcs = [
    "leetcode237_delete_node_in_a_linked_list.cc"
  ],
  deps = [
    ":leetcode_link_list_node",
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 242: Valid Anagram
cc_test(
  name = "leetcode242",
  srcs = [
    "leetcode242_valid_anagram.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)

# Leetcode 292: Nim Game
cc_test(
  name = "leetcode292",
  srcs = [
    "leetcode292_nim_game.cc"
  ],
  deps = [
    "@com_google_googletest//:gtest_main",
  ]
)