# POJ1003: Hangover
cc_library(
  name = "poj1003_solve",
  hdrs = ["poj1003.hpp"]
)

cc_binary(
  name = "poj1003",
  srcs = [
    "poj1003.cc"
  ],
  deps = [
    ":poj1003_solve"
  ]
)

cc_test(
  name = "poj1003_test",
  srcs = [
    "poj1003_test.cc"
  ],
  deps = [
    ":poj1003_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1004: Financial Management
cc_library(
  name = "poj1004_solve",
  hdrs = ["poj1004.hpp"]
)

cc_binary(
  name = "poj1004",
  srcs = [
    "poj1004.cc"
  ],
  deps = [
    ":poj1004_solve"
  ]
)

cc_test(
  name = "poj1004_test",
  srcs = [
    "poj1004_test.cc"
  ],
  deps = [
    ":poj1004_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1005: I Think I Need a Houseboat
cc_library(
  name = "poj1005_solve",
  hdrs = ["poj1005.hpp"]
)

cc_binary(
  name = "poj1005",
  srcs = [
    "poj1005.cc"
  ],
  deps = [
    ":poj1005_solve"
  ]
)

cc_test(
  name = "poj1005_test",
  srcs = [
    "poj1005_test.cc"
  ],
  deps = [
    ":poj1005_solve",
    "@com_google_googletest//:gtest_main",
  ]
)

# POJ1007: DNA Sorting
cc_library(
  name = "poj1007_solve",
  hdrs = ["poj1007.hpp"]
)

cc_binary(
  name = "poj1007",
  srcs = [
    "poj1007.cc"
  ],
  deps = [
    ":poj1007_solve"
  ]
)

cc_test(
  name = "poj1007_test",
  srcs = [
    "poj1007_test.cc"
  ],
  deps = [
    ":poj1007_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1012: Joseph
cc_library(
  name = "poj1012_solve",
  hdrs = ["poj1012.hpp"]
)

cc_binary(
  name = "poj1012",
  srcs = [
    "poj1012.cc"
  ],
  deps = [
    ":poj1012_solve"
  ]
)

cc_test(
  name = "poj1012_test",
  srcs = [
    "poj1012_test.cc"
  ],
  deps = [
    ":poj1012_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1207: The 3n + 1 problem
cc_library(
  name = "poj1207_solve",
  hdrs = ["poj1207.hpp"]
)

cc_binary(
  name = "poj1207",
  srcs = [
    "poj1207.cc"
  ],
  deps = [
    ":poj1207_solve"
  ]
)

cc_test(
  name = "poj1207_test",
  srcs = [
    "poj1207_test.cc"
  ],
  deps = [
    ":poj1207_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1258: Agri-Net
cc_library(
  name = "poj1258_solve",
  hdrs = ["poj1258.hpp"]
)

cc_binary(
  name = "poj1258",
  srcs = [
    "poj1258.cc"
  ],
  deps = [
    ":poj1258_solve"
  ]
)

cc_test(
  name = "poj1258_test",
  srcs = [
    "poj1258_test.cc"
  ],
  deps = [
    ":poj1258_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1338: Ugly Numbers
cc_library(
  name = "poj1338_solve",
  hdrs = ["poj1338.hpp"]
)

cc_binary(
  name = "poj1338",
  srcs = [
    "poj1338.cc"
  ],
  deps = [
    ":poj1338_solve"
  ]
)

cc_test(
  name = "poj1338_test",
  srcs = [
    "poj1338_test.cc"
  ],
  deps = [
    ":poj1338_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1363: Rails
cc_library(
  name = "poj1363_solve",
  hdrs = ["poj1363.hpp"]
)

cc_binary(
  name = "poj1363",
  srcs = [
    "poj1363.cc"
  ],
  deps = [
    ":poj1363_solve"
  ]
)

cc_test(
  name = "poj1363_test",
  srcs = [
    "poj1363_test.cc"
  ],
  deps = [
    ":poj1363_solve",
    "@com_google_googletest//:gtest_main",
  ]
)
