# POJ1004: Financial Management
cc_library(
  name = "poj1004_solve",
  hdrs = ["poj1004.hpp"]
)

cc_binary(
  name = "poj1004",
  srcs = [
    "poj1004.cc"
  ],
  deps = [
    ":poj1004_solve"
  ]
)

cc_test(
  name = "poj1004_test",
  srcs = [
    "poj1004_test.cc"
  ],
  deps = [
    ":poj1004_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1007: DNA Sorting
cc_library(
  name = "poj1007_solve",
  hdrs = ["poj1007.hpp"]
)

cc_binary(
  name = "poj1007",
  srcs = [
    "poj1007.cc"
  ],
  deps = [
    ":poj1007_solve"
  ]
)

cc_test(
  name = "poj1007_test",
  srcs = [
    "poj1007_test.cc"
  ],
  deps = [
    ":poj1007_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1012: Joseph
cc_library(
  name = "poj1012_solve",
  hdrs = ["poj1012.hpp"]
)

cc_binary(
  name = "poj1012",
  srcs = [
    "poj1012.cc"
  ],
  deps = [
    ":poj1012_solve"
  ]
)

cc_test(
  name = "poj1012_test",
  srcs = [
    "poj1012_test.cc"
  ],
  deps = [
    ":poj1012_solve",
    "@com_google_googletest//:gtest_main",
  ]
)


# POJ1207: The 3n + 1 problem
cc_library(
  name = "poj1207_solve",
  hdrs = ["poj1207.hpp"]
)

cc_binary(
  name = "poj1207",
  srcs = [
    "poj1207.cc"
  ],
  deps = [
    ":poj1207_solve"
  ]
)

cc_test(
  name = "poj1207_test",
  srcs = [
    "poj1207_test.cc"
  ],
  deps = [
    ":poj1207_solve",
    "@com_google_googletest//:gtest_main",
  ]
)
